package com.archermind.note.Events;

public enum EventTypes {
	EVENT_TEST,
	TITLE_BAR_CALENDER_CLICKED,
	TITLE_BAR_NOTEBOOK_CLICKED,
	TITLE_BAR_NOTE_ALBUM_CLICKED,
	NEW_NOTE_BUTTON_CLICKED,
	HOMESCREEN_FLING,
}
