package com.archermind.note.Events;

public enum EventTypes {
	EVENT_TEST,
	TITLE_BAR_CALENDER_CLICKED,
	TITLE_BAR_NOTEBOOK_CLICKED,
	TITLE_BAR_NOTE_ALBUM_CLICKED,
	NEW_NOTE_BUTTON_CLICKED,
	HOMESCREEN_FLING,
	SHOW_ONEDAY_NOTES,
	SHOW_OR_HIDE_BUTTON_BACK,
	HOME_SCREEN_ONEDAY_NOTE_BACK_PRESSED,
	MAIN_SCREEN_UPDATE_TITLE,
}
