package com.archermind.note.Events;

public enum EventTypes {
	EVENT_TEST,
	TITLE_BAR_CALENDER_CLICKED,
	TITLE_BAR_NOTEBOOK_CLICKED,
	TITLE_BAR_NOTE_ALBUM_CLICKED,
	NEW_NOTE_BUTTON_CLICKED,
	HOMESCREEN_FLING,
	NOTE_INSERT_TO_DATABASE,
	NOTE_UPDATE_TO_DATABASE,
	SHOW_ONEDAY_NOTES,
	SHOW_OR_HIDE_BUTTON_BACK,
	HOME_SCREEN_ONEDAY_NOTE_BACK_PRESSED,
	MAIN_SCREEN_UPDATE_TITLE,
	SHARE_NOTE_SUCCESSED,
	SHARE_NOTE_FAILED,
	NOTE_PIC_SAVE_OVER,
	NOTE_TO_BE_SHARE,
	NOTE_SAVE_OVER,
}
